kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: oc-template
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/component: ${APP_NAME}
        app.kubernetes.io/instance: ${APP_NAME}
        app.kubernetes.io/name: ${APP_NAME}
        app.kubernetes.io/part-of: ${GROUP_APP_NAME}-app
      name: ${APP_NAME}
      namespace: ${NS_NAME}
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      replicas: 1
      revisionHistoryLimit: 5
      selector:
        matchLabels:
          app: ${APP_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
        spec:
          containers:
            - image: ${IMAGE_NAME}
              imagePullPolicy: Always
              name: ${APP_NAME}
              args:
                - 'Xmx500m'
                - 'XX:+PrintGC'
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-cm
              resources:
                limits:
                  cpu: 400m
                  memory: 500Mi
                requests:
                  cpu: 250m
                  memory: 350Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              readinessProbe:
                httpGet:
                  path: /actuator/health/readiness
                  port: 8080
                failureThreshold: 3
                initialDelaySeconds: 90
                periodSeconds: 60
              livenessProbe:
                httpGet:
                  path: /actuator/health/liveness
                  port: 8080
                failureThreshold: 3
                initialDelaySeconds: 90
                periodSeconds: 60
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${APP_NAME}-cm
      namespace: ${NS_NAME}
    data:
      TZ: "Asia/Jakarta"
      URI_DB_HOST: "192.168.132.81:1572:gwdev"
      DB_USER: "ugwadmin"
      DB_PASS: "ugwadmin"

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        haproxy.router.openshift.io/timeout: 40s
      name: ${APP_NAME}
      namespace: ${NS_NAME}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/component: ${APP_NAME}
        app.kubernetes.io/instance: ${APP_NAME}
        app.kubernetes.io/name: ${APP_NAME}
        app.kubernetes.io/part-of: ${GROUP_APP_NAME}-app
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${APP_NAME}
        weight: 100
      wildcardPolicy: None
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: ${APP_NAME}
      namespace: ${NS_NAME}
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: ${APP_NAME}
      minReplicas: 1
      maxReplicas: 5
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              averageUtilization: 85
              type: Utilization
  #        - type: Resource
  #          resource:
  #            name: memory
  #            target:
  #              averageUtilization: 85
  #              type: Utilization
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APP_NAME}
      namespace: ${NS_NAME}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/component: ${APP_NAME}
        app.kubernetes.io/instance: ${APP_NAME}
        app.kubernetes.io/name: ${APP_NAME}
        app.kubernetes.io/part-of: ${GROUP_APP_NAME}-app
    spec:
      selector:
        app: ${APP_NAME}
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
parameters:
  - name: NS_NAME
    description: namespace name
    required: true
    value: "kong-dev"
  - name: IMAGE_NAME
    description: image name
    required: true
    value: "jtl-tkgiharbor.hq.bni.co.id/wss-dev/bank-hellen-app:version1"
  - name: APP_NAME
    description: application name
    required: true
    value: "bank-hellen-app"
  - name: GROUP_APP_NAME
    description: group application name
    value: "BANK-HELLEN"